services:
  zookeeper:
    image: bitnami/zookeeper:3.9.2
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - 2181:2181

  kafka:
    image: bitnami/kafka:3.7.0
    depends_on:
      - zookeeper
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    ports:
      - 9092:9092

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  trainer:
    build: ./trainer
    depends_on:
      - redis
    volumes:
      - ./trainer:/app
    command: ["python", "trainer.py"]

  producer:
    build: ./producer
    depends_on:
      - kafka
    volumes:
      - ./producer:/app
    command: ["python", "producer.py"]

  consumer:
    build: ./consumer
    depends_on:
      - kafka
      - redis
    volumes:
      - ./consumer:/app
    command: ["python", "scoring_consumer.py"]

  api:
    build: ./api
    depends_on:
      - redis
    ports:
      - 8000:8000
    volumes:
      - ./api:/app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
